name: build-kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/morosakubek2/android_kernel_samsung_b2q
          kernel-branch: main
          config: b2q_eur_openx_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
   
